version: "3"

services:
  node:
    image: node:16
    container_name: desafio_xp
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_DATABASE: desafio_xp
      JWT_SECRET: secretJWT

  db:
    container_name: desafio_xp__db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: desafio_xp

networks:
  default:
    name: desafio_xp_net
